on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: 'main test'

env:
  REGISTRY_REPO: zhu733756/fluentbit-buildtools
  REGISTRY_TAG: v1.9.2

jobs:
  build:
    name: build
    runs-on: ubuntu-18.04
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      
      - name: build
        run: |
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
          docker buildx build . --platform linux/arm64/v8,linux/amd64 --push -f Dockerfile -t ${{ env.REGISTRY_REPO}}:${{ env.REGISTRY_TAG }}

  check:
    name: pre-check
    runs-on: ubuntu-18.04
    timeout-minutes: 30
    steps:
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          severity: error

      - name: Check path
        run: | 
          ls /var/log/journal
          ls /var/log/containers
    
  centos7-amd64:
    name: centos7-amd64-test
    runs-on: ubuntu-18.04
    timeout-minutes: 30
    needs: ["build", "check"]
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup cluster
      run: | 
        export INSTALL_KIND=yes && INSTALL_HELM=yes && chmod a+x ./setup-cluster.sh && ./setup-cluster.sh

    - name: Setup kafka
      run: | 
        chmod a+x ./setup-kafka.sh && ./setup-kafka.sh

    - name: Run centos7, Setup fluentbit, send logs to kafka
      run: |
        docker run -d  -v /var/log/journal:/var/log/journal -v /var/log/container:/var/log/container --platform linux/amd64 --name centos7 --net="host" ${{ env.REGISTRY_REPO}}:${{ env.REGISTRY_TAG }}
        docker exec -it centos7 bash -c "tail -n 100 /etc/fluent-bit/logs/fluent-bit.log"

    - name: Listening topics
      run: |
        kubectl -n kafka exec -it my-cluster-kafka-0 -- bin/kafka-console-consumer.sh --bootstrap-server my-cluster-kafka-bootstrap:9092 --topic test & { sleep 60; kill $! & }

  centos7-arm64:
    name: centos7-arm64-test
    runs-on: ubuntu-18.04
    timeout-minutes: 30
    needs: ["build", "check"]
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup cluster
      run: | 
        export INSTALL_KIND=yes && INSTALL_HELM=yes && chmod a+x ./setup-cluster.sh && ./setup-cluster.sh

    - name: Setup kafka
      run: | 
        chmod a+x ./setup-kafka.sh && ./setup-kafka.sh

    - name: Run centos7, Setup fluentbit, send logs to kafka
      run: |
        docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
        docker run -d -v /var/log/journal:/var/log/journal -v /var/log/container:/var/log/container --platform linux/arm64/v8 --name centos7 --net="host" ${{ env.REGISTRY_REPO}}:${{ env.REGISTRY_TAG }}
        docker exec -it centos7 bash -c "tail -n 100 /etc/fluent-bit/logs/fluent-bit.log "

    - name: Listening topics
      run: |
        kubectl -n kafka exec -it my-cluster-kafka-0 -- bin/kafka-console-consumer.sh --bootstrap-server my-cluster-kafka-bootstrap:9092 --topic test & { sleep 60; kill $! & }
 